schema_version = 1

[[plugins]]
id = "threejs"
name = "Three.js"
version = "0.184.0"
api_global = "window.SfumatoPlugins.threejs"
runtime = "threejs/runtime.js"
guidance = "threejs/usage.md"
license = "threejs/LICENSE"
runtime_hash = "996a42047a27414eac7ee29e7b79752cbe209cab5a6496dad50ec8973a5353c7"

[[plugins]]
id = "motion"
name = "Motion"
version = "12.42.2"
api_global = "window.SfumatoPlugins.motion"
runtime = "motion/runtime.js"
guidance = "motion/usage.md"
license = "motion/LICENSE"
runtime_hash = "5f3c65c6e12ced46599d323e554f6745e25a90874aa570b65b83e6158054c426"

[[plugins]]
id = "theatre"
name = "Theatre.js Core"
version = "0.7.2"
api_global = "window.SfumatoPlugins.theatre"
runtime = "theatre/runtime.js"
guidance = "theatre/usage.md"
license = "theatre/LICENSE"
runtime_hash = "4f5a279adc60862a716eca41b06436d61db98cd5bec39255b828da914f02bde6"

[[plugins]]
id = "lottie"
name = "Lottie Web"
version = "5.13.0"
api_global = "window.SfumatoPlugins.lottie"
runtime = "lottie/runtime.js"
guidance = "lottie/usage.md"
license = "lottie/LICENSE"
runtime_hash = "c1692e2d55306d3ecaee85885327e0af5155e08c6a30e15236f91d6972d22ade"

[[plugins]]
id = "react"
name = "React"
version = "18.3.1"
api_global = "window.React"
runtime = "react/runtime.js"
guidance = "react/usage.md"
license = "react/LICENSE"
runtime_hash = "d949f1c3687aedadcedac85261865f29b17cd273997e7f6b2bfc53b2f9d4c4dd"
category = "runtime"

[[plugins]]
id = "react-dom"
name = "ReactDOM"
version = "18.3.1"
api_global = "window.ReactDOM"
runtime = "react-dom/runtime.js"
guidance = "react-dom/usage.md"
license = "react-dom/LICENSE"
runtime_hash = "35f4f974f4b2bcd44da73963347f8952e341f83909e4498227d4e26b98f66f0d"
category = "runtime"
dependencies = ["react"]

[[plugins]]
id = "materialui"
name = "Material UI"
version = "5.15.14"
api_global = "window.MaterialUI"
runtime = "materialui/runtime.js"
guidance = "materialui/usage.md"
license = "materialui/LICENSE"
runtime_hash = "57ea6921e62da4fe6aad1b50241d72700ae95f611f9e6932ee9d11a5f45e6df0"
category = "ui"
dependencies = ["react-dom"]
