classDiagram
    namespace Presentation {
        class Cli {
            +Commands command
        }
        class Commands {
            <<enum>>
            Init
            Config
            Project
            Connector
            Model
            Theme
            Generate
        }
        class RunnableCommand {
            <<trait>>
            +run() Result
        }
        class InteractiveMenu
        class InitPrompts
        class OutputFormatter
    }

    namespace CoreServices {
        class SetupService
        class ConfigService
        class ProjectService
        class ConnectorService
        class ModelService
        class ThemeService
        class SlidesPipeline
        class SlideReviewPipeline
        class FilesystemToolExecutor
        class ImageGenerationTool
    }

    namespace RepositoryPorts {
        class GlobalConfigRepository {
            <<trait>>
            +load() GlobalConfig
            +save(GlobalConfig)
        }
        class ProjectRepository {
            <<trait>>
            +registry() ProjectRegistry
            +load(name) ProjectConfig
            +save(ProjectConfig)
            +register(name, path, activate)
            +remove(name)
        }
        class ThemeRepository {
            <<trait>>
            +list() ThemeSummary[]
            +load(name) ThemePackage
            +create(name) ThemePackage
            +install_default() ThemePackage
        }
    }

    namespace FilesystemAdapters {
        class FilesystemGlobalConfigRepository
        class FilesystemProjectRepository
        class FilesystemThemeRepository
        class MarpRenderer
        class MarpLayoutInspector
        class MermaidDiagramRenderer
        class SourceReader
        class ArtifactWriter
    }

    namespace Domain {
        class GlobalConfig
        class ProjectRegistry
        class ProjectConfig
        class EffectiveConfig
        class ModelProfile
        class ModelRole {
            <<enum>>
            Reviewer
        }
        class SlideReviewSummary
        class SlideLayoutIssue
        class ReviewableDocument {
            <<trait>>
            +snapshot() ReviewSnapshot
            +apply_patch(JsonPatch) PatchReport
            +validate() ValidationReport
            +render() String
        }
        class ReviewSnapshot
        class PatchReport
        class SlideDeckDocument
        class SlideDocument
        class SlideElement {
            <<enum>>
            Paragraph
            List
            Code
            Mermaid
            Math
            Table
            Image
            PresenterNotes
        }
        class SlideRange
        class SlideReplacement
        class ThemePackage
        class GenerationRequest
        class GenerationOutput
        class GenerationToolSummary
    }

    namespace ProviderAdapters {
        class TextGenerationProvider {
            <<trait>>
            +generate_text(request) TextGenerationResponse
        }
        class ImageGenerationProvider {
            <<trait>>
            +generate_image(request) ImageGenerationResponse
        }
        class ToolExecutor {
            <<trait>>
            +execute(request) String
        }
        class ToolDefinition
        class OpenAiCompatibleTextProvider
        class OpenAiCompatibleImageProvider
        class OpenAiCompatibleConnector
    }

    Cli *-- Commands
    Commands ..|> RunnableCommand
    InteractiveMenu --> Commands
    InitPrompts --> SetupService
    Commands --> SetupService
    Commands --> ConfigService
    Commands --> ProjectService
    Commands --> ConnectorService
    Commands --> ModelService
    Commands --> ThemeService
    Commands --> SlidesPipeline
    OutputFormatter --> GenerationOutput

    SetupService --> GlobalConfigRepository
    ProjectService --> ProjectRepository
    ConnectorService --> GlobalConfigRepository
    ModelService --> GlobalConfigRepository
    ModelService --> ProjectRepository
    ThemeService --> ThemeRepository
    ThemeService --> ProjectRepository
    ConfigService --> GlobalConfig
    ConfigService --> ProjectConfig

    FilesystemGlobalConfigRepository ..|> GlobalConfigRepository
    FilesystemProjectRepository ..|> ProjectRepository
    FilesystemThemeRepository ..|> ThemeRepository

    GlobalConfigRepository --> GlobalConfig
    ProjectRepository --> ProjectRegistry
    ProjectRepository --> ProjectConfig
    ThemeRepository --> ThemePackage

    SlidesPipeline --> GenerationRequest
    SlidesPipeline --> GenerationOutput
    GenerationOutput --> SlideReviewSummary
    SlideReviewSummary --> SlideLayoutIssue
    GenerationOutput --> GenerationToolSummary
    SlidesPipeline --> EffectiveConfig
    SlidesPipeline --> ThemeService
    SlidesPipeline --> TextGenerationProvider
    SlidesPipeline --> SlideReviewPipeline
    SlideReviewPipeline --> ModelRole
    SlideReviewPipeline --> TextGenerationProvider
    SlideReviewPipeline --> ReviewSnapshot
    SlideReviewPipeline --> ReviewableDocument
    SlideDeckDocument ..|> ReviewableDocument
    SlideDeckDocument *-- SlideDocument
    SlideDocument *-- SlideElement
    ReviewableDocument --> PatchReport
    SlideReviewPipeline --> MarpLayoutInspector
    SlideReviewPipeline --> SlideRange
    SlideReviewPipeline --> SlideReplacement
    SlideReplacement --> SlideRange
    MarpLayoutInspector --> MarpRenderer
    MarpLayoutInspector --> MermaidDiagramRenderer
    SlidesPipeline --> SourceReader
    SlidesPipeline --> ArtifactWriter
    SlidesPipeline --> MarpRenderer
    SlidesPipeline --> MermaidDiagramRenderer
    SlidesPipeline --> FilesystemToolExecutor
    SlidesPipeline --> ImageGenerationTool

    OpenAiCompatibleTextProvider ..|> TextGenerationProvider
    OpenAiCompatibleImageProvider ..|> ImageGenerationProvider
    OpenAiCompatibleTextProvider --> ToolDefinition
    OpenAiCompatibleTextProvider --> ToolExecutor
    OpenAiCompatibleTextProvider --> OpenAiCompatibleConnector
    OpenAiCompatibleImageProvider --> OpenAiCompatibleConnector
    OpenAiCompatibleTextProvider --> ModelProfile
    FilesystemToolExecutor ..|> ToolExecutor
    ImageGenerationTool --> ImageGenerationProvider
